trigger:
- master

pool:
  vmImage: 'windows-latest'


variables:
  LT_USERNAME: 'username'
  LT_ACCESS_KEY: 'accesskey'
  LT_BUILD_NAME: 'buildName'

# Maven
steps:

- task: Maven@3
- task: LambdatestResults@1
