name: Java CI with Maven

- task: LambdatestResults@1
- task: Maven@4
  inputs:
    mavenPomFile: 'single.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        export MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=4096m"
        _JAVA_OPTIONS="-Xmx3G" mvn test -D suite=single.xml