trigger:
- master

pool:
  vmImage: 'windows-latest'


variables:
  LT_USERNAME: 'rakeshslambdatest'
  LT_ACCESS_KEY: 'MHu1nfiZVVPSteHsFVqybmvsxePoFJq0j8htKDk7uHcRwPgLGg'
  LT_BUILD_NAME: 'buildName'

# Maven
steps:

- task: Maven@3