trigger:
- master

pool:
  vmImage: windows-latest

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    # pool:
    #   name: Default
    steps:
      - task: Maven@3
      # - task: LambdatestResults@1

- stage: Release
  displayName: Release
  jobs:
  - job: Release
    # pool:
    #   name: Default
    steps:               
      - task: Maven@3
      # - task: LambdatestResults@1

- stage: Quilter
  displayName: Quilter
  jobs:
  - job: Quilter
    # pool:
    #   name: Default
    steps:               
      # - task: Maven@3
      - task: LambdatestResults@1